### ISSUE TITLE
zram-init fails if zramctl is available but no zstd support

### ISSUE THREAD

**Issue by sedlund** [vaeth/zram-init#15]
Same system as in #14 but now with util-linux installed for zramctl suport.

No log, except on console.

![image](https://user-images.githubusercontent.com/8109138/53708573-0b192500-3e6f-11e9-9af5-73f230512e61.png)

In this case with zramctl installed, it will not create a zram device at all.

zramctl in Alpine 3.9.1:

```
alpine@ip-172-31-43-27:$ zramctl -V
zramctl from util-linux 2.33
alpine@ip-172-31-43-27:$ zramctl --help

Usage:
 zramctl [options] <device>
 zramctl -r <device> [...]
 zramctl [options] -f | <device> -s <size>

Set up and control zram devices.

Options:
 -a, --algorithm **lzo|lz4|lz4hc|deflate|842**   compression algorithm to use
...

alpine@ip-172-31-43-27:~$ cat /proc/swaps
Filename                                Type            Size    Used    Priority


```
No zstd support.

Maybe defaulting to zstd in the default /etc/conf.d/zram-init might be a bit premature.

**Comment by vaeth** [comment]
The algorithms shown on the help page of zramctl are not the algorithms which it understands:
zramctl simply attempts to set the passed algorithm argument.
The error message you see is from the kernel: It seems your kernel does not have support for zstd compiled into the zram module. (Or maybe it exists only as a module and you have to modprobe something before?)

**Comment by sedlund** [comment]
There is a loaded zstd module for btrfs.  The alpine kernel seems not to include support for it with zram though, as evidenced by the output from the other issue I posted.

**Comment by sedlund** [comment]
Oops did not mean to close!

**Comment by vaeth** [comment]
IMHO, this is not a bug. It is documented which kernel versions can provide support.

Having zstd support in the kernel is not enough for zram. It must also be supported by the crypto API, that is, you will need CONFIG_CRYPTO_ZSTD.

**Comment by sedlund** [comment]
Thanks for your help with the other things.  I will raise this one in the Alpine bug tracker.

**Comment by sedlund** [comment]
zram support is now compiled in recent alpine kernels.

https://git.alpinelinux.org/aports/commit/?id=4fcd763003fabfbff087413bd82d767b1862b6f9

thanks.
