### ISSUE TITLE
Provide improved documentation of the config file

### ISSUE THREAD

**Issue by SharkWipf** [vaeth/zram-init#28]
Currently, the service config file's documentation has a bunch of flags that aren't explained properly, if at all.
Which, for the config file, is fine, but they are not documented anywhere else, either.

For example, the backup device flags, the only documentation provides is:
```bash
# back0, back1, ... are the variables for the backup device
# icmp0, icmp1, ... are the flags (if nonempty) for writing incompressible
#                   pages to the backup device (requires setting back*)
# idle0, idle1, ... are the flags (in nonempty) for writing idle pages to the
#                   backup device (requires setting back*)
# wlim0, wlim1, ... set the writeback_limit for idle pages (implies idle*)

[...]

back0= # no backup device
icmp0= # no incompressible page writing to backup device
idle0= # no idle page writing to backup device
wlim0= # no writeback_limit for idle page writing for backup device
```
Nothing tells me what, exactly, I should be entering on `icmp0` or `idle0` to enable it. Do I enter a boolean? An int? The backup device path?
The man page doesn't touch on the config file at all, and no external documentation appears to be present.

**Comment by vaeth** [comment]
Fixed in zram-init-10.6.
