### ISSUE TITLE
zram-init -M and -2 don't work

### ISSUE THREAD

**Issue by GimmeHardware** [vaeth/zram-init#34]
In zram-init the -M and -2 switches don't work. Assuming push.sh is available the arguments are gathered and processed into positional args but they're never passed to mount or tune2fs because there's a ${1:+"$@"} missing from the mount command lines (all four supported filesystems) and the tune2fs command lines (ext2 and ext4).

**Comment by vaeth** [comment]
Thanks for the report. This should be fixed in v10.12
