### ISSUE TITLE
openrc zram-init ignores typeN=- devices

### ISSUE THREAD

**Issue by allixx** [vaeth/zram-init#38]
When there is a device configured as typeN=- in /etc/conf.d/zram-init, it is completely ignored by zram-init openrc script.

According to the docs, typeN=- is a supported type, meaning that device and filesystem will be created, but not mounted.

It seems that case arg is missing a - variant here:
https://github.com/vaeth/zram-init/blob/main/openrc/init.d/zram-init#L72
and that line should be changed to:
```
	swap|/*|-)
```
After applying this change, typeN=- devices are created as described in docs.

**Comment by vaeth** [comment]
Fixed in zram-init-11.1.
