### ISSUE TITLE
sys-block/zram-init should be configured so that there is one service per mount point or swap configuration

### ISSUE THREAD

**Issue by anoldgeek** [vaeth/zram-init#40]
Configure sys-block/zram-init so that there is one service per mount point or swap configuration, in a similar manner that net-misc/tigervnc does per display.
This would enable:
1. starting and stopping each config separately.
2. Configuring separate writeback daemons for each config.

**Comment by vaeth** [comment]
It makes no sense to make the services even more generic only to cover a rather non-generic use-case. The proper solution for such a special use case is to write your own init scripts, possibly making use of the zram-init script as a wrapper for convenience.
