### ISSUE TITLE
[Feature] Please add support for mkfs options / device labels

### ISSUE THREAD

**Issue by olifre** [vaeth/zram-init#8]
It would be nice if options could be passed to mkfs through the zram-init config file. 

One option I am missing is for example the possibility to set a filesystem label such that graphical file explorers (Dolphin etc.) show that label instead of something like "24 GB device", which is their default for nameless filesystems. 

Thanks for the beautiful tool and cheers, 
Oliver

**Comment by vaeth** [comment]
The new release 4.0.0 supports -L and -U options for label and uuid.
It also supports passing of generic args to all utilities if push.sh from https://github.com/vaeth/push/ is in $PATH

**Comment by olifre** [comment]
Thanks a lot for the fast and perfect solution, working fine :).
